#this file defines the "servers" our data pipeline will use 
#we will run this file with the command: docker-compose up -d

version: '3.7'

services:
#1. Zookeeper: Kafka needs this to manage its state.
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICKTIME: 2000

#2. Kafka:Our high-speed message queue(the "inbox")
  kafka:  
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on: 
      - zookeeper  
    ports:  
      #this line makes kafka accesible from your python scrypt
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  #3. OUR DATABASE: POSTGRES WITH THE TIMESCALEDB EXTENSIONS
  #THIS IS MUCH, MUCH BETTER FOR TIME-SERIES DATA THAN A CSV.
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
    #this line makse the database accessible from the python script
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketdata





